version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: springbootuser
      MYSQL_PASSWORD: springbootpassword

  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springbootdb
      SPRING_DATASOURCE_USERNAME: springbootuser
      SPRING_DATASOURCE_PASSWORD: springbootpassword
    depends_on:
      - mysql
